import { useEffect } from "react";
import { useLocation } from "react-router";

export function ManifestManager() {
  const location = useLocation();

  useEffect(() => {
    const isAdmin = location.pathname.includes("admin-zara");
    const manifestLink = document.querySelector('link[rel="manifest"]');
    const appleTitle = document.querySelector('meta[name="apple-mobile-web-app-title"]');

    if (manifestLink) {
      const newManifest = isAdmin ? "manifest-admin.webmanifest" : "manifest.webmanifest";
      // We assume manifest.webmanifest is generated by VitePWA
      manifestLink.setAttribute("href", isAdmin ? `/salon_app/${newManifest}` : "/salon_app/manifest.webmanifest");
    }

    if (appleTitle) {
      appleTitle.setAttribute("content", isAdmin ? "Zara Admin" : "Zara Beauté");
    }

    // Force browser to notice manifest change (standard trick)
    if (manifestLink) {
      const parent = manifestLink.parentNode;
      if (parent) {
        const next = manifestLink.nextSibling;
        parent.removeChild(manifestLink);
        parent.insertBefore(manifestLink, next);
      }
    }
  }, [location.pathname]);

  return null;
}
